Fix converting scientific notated floats
Convert float values in scientific notation (like `1e-06`) to `float` instead of `BigInt`/integer, which at the moment causes errors like:
```
SyntaxError: Cannot convert 1e-06 to a BigInt
```